### PR TITLE
fixing `columnState` for use with React 18

### PR DESCRIPTION
**Pull request by BSd3v**
* migrated props that use `setProps` from `render()` to `componentDidUpdate` (this fixed the `bad setState()` error)
* adjusted `columnState` if statement to use `prevProps.loading_state`

### CODE REVIEW

**Comment by alexcjohnson** [comment]
This looks great. I wonder though, do we need to call out to these same updaters in `componentDidMount`? Like what if you want your grid to start out scrolled to a specific row?

**Comment by BSd3v** [comment]
The grid can't do things like that until it is ready, which updates the grid's state. Which then triggers the event if the prevState had a null gridApi and the current one has a gridApi.

**Comment by BSd3v** [comment]
Also, there is already a test for starting out on a scrolled row, as well as with an initial columnState.

**Review by alexcjohnson — APPROVED** [review]
💃

**Pull request merged**
