### PR TITLE
fix for JSON Parse error when using dash_ag_grid and dash pages

### LINKED ISSUE #299: JSON Parse error when using dash_ag_grid and dash pages
```
dash                           2.16.1
dash_ag_grid                   31.0.1
dash-bootstrap-components      1.5.0
dash-core-components           2.0.0
dash-html-components           2.0.0
dash-mantine-components        0.12.1
dash-table                     5.0.0
dash-testing-stub              0.0.2

```

**Description**

Set up two dash pages. One should contain `dash_ag_grid`.
Run the app, open the page with `dash_ag_grid` and quickly (in 1 second) switch to different page.
Next error occurs in browser console:
```
SyntaxError: JSON Parse error: Unexpected identifier "undefined"
```

**Expected behavior**

No console error occurred

**Screenshots**

image

### PR DESCRIPTION
**Pull request by BSd3v**
Fixes #299.

* testing for grid destroyed before trying to get the state

### CODE REVIEW

**Comment by gvwilson** [comment]
@archmoj could you please have a look at this (or let us know that you don't feel you have enough context to review)?

**Comment by archmoj** [comment]
@BSd3v Thanks very much for the PR. It's looking good. 
Could you add a test to lock down this bug from happening again?

@gvwilson I am not familiar with this repository. 
By looking at [the list of contributors](https://github.com/plotly/dash-ag-grid/graphs/contributors) @AnnMarieW, @ndrezn and @Farkites may help approving this PR.

BTW. I was wondering perhaps this check could/should be moved to be inside `getColumnState` as an early return to avoid duplicates and simplify this PR as well.

**Comment by BSd3v** [comment]
Hello @archmoj,

`getColumnState` is not something that this repository owns as it comes from the underlying AG Grid. While yes they could do a return, they provide the warning that you are calling a function against a destroyed grid.

**Review by AnnMarieW — APPROVED** [review]
:woman_dancing: 

Looks good!

**Pull request merged**
