### PR TITLE
bumping to AG Grid version 31.3

### PR DESCRIPTION
**Pull request by BSd3v**

### CODE REVIEW

**Comment by ndrezn** [comment]
@BSd3v #328 supersede this?

**Comment by BSd3v** [comment]
Nope, I would like to release both. 32.2 needs to be tested, and possible some documentation changes as well.

31.3 wont require doc changes.

**Review by gvwilson — APPROVED** [review]

**Comment by aliwelchoo** [comment]
Is it possible to create a build for 31.3 before going straight to 32.2? I need to use `grandTotalRow` so if 31.3 could be released I'd really appreciate it?

**Comment by BSd3v** [comment]
This is the plan, but I am not in control of releases.

**Pull request merged**
